version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src/:/app/src
    ports:
      - "8000:8000"
    environment:
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET=${DJANGO_SECRET}

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./src/static/:/home/static